assistant_task:
  description: >
    Analyze the user's message. The user's message is: {user_message}. Here is the context of our conversation: {context}. 
    Determine if a CV or a Job Description is provided in the message. If both CV and Job Description are provided, 
    provide a score (out of 10) for how well the CV matches the job description, and provide 2-3 specific, actionable suggestions to improve the CV. 
    If either the CV or Job Description is missing, or if the user has not provided any information related to the CV evaluation, 
    then respond appropriately and maintain the flow of the conversation. This might involve asking for clarification,
    asking for more information, or responding to a greeting.
  expected_output: >
    Your output should include:
    - If both CV and Job Description were present:
        - A score out of 10 for the CV's fit to the job description.
        - 2-3 actionable suggestions for CV improvement.
    - If either or both are missing, or the user query is not about CV evaluation, then your response should either be asking for the required information
      or addressing the user query appropriately. Maintain the conversation flow appropriately.
